name: poilfix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sizer: ^2.0.15
  http: ^0.13.4
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11
  hydrated_bloc: ^8.1.0
  share_plus: ^4.0.10
  validators: ^3.0.0
  stream_transform: ^2.0.0
  image_picker: ^0.8.3+3   # may remove
  url_launcher: ^6.1.5
  awesome_notifications: ^0.7.4+1
  connectivity_wrapper: ^1.1.0
  parse_server_sdk_flutter: ^3.1.3
  firebase_messaging: ^14.1.3
  firebase_core: ^2.3.0
  device_info_plus: ^5.0.5
  shimmer: ^2.0.0
  loading_animation_widget: ^1.2.0+3
  line_icons: ^2.0.0
  money_formatter: ^0.0.3
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.0


flutter:
  generate: true #run command:  flutter gen-l10n
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_background: "assets/images/logo.png"
  ios: true
  image_path: "assets/images/logo.png"
# command : flutter pub run flutter_launcher_icons

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"

# command : flutter pub run flutter_native_splash:create
