// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbuVMvAEdw7XyKCqMwtFD3RiALjHHHr0',
    appId: '1:592632828821:android:975e485d426ed4b7475c9c',
    messagingSenderId: '592632828821',
    projectId: 'piolfix-123',
    storageBucket: 'piolfix-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCY1U7X_sPMVkccakMAY8ZWsZtlsAkfAg',
    appId: '1:592632828821:ios:290882cdf3147bea475c9c',
    messagingSenderId: '592632828821',
    projectId: 'piolfix-123',
    storageBucket: 'piolfix-123.appspot.com',
    androidClientId: '592632828821-cpe6hk205n15mt1dvlrva9sttno1vs1p.apps.googleusercontent.com',
    iosClientId: '592632828821-es56flgdpgme1g4ucmm5upedep7t7jhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.piolfix',
  );
}
